-- 코드를 작성해주세요

SELECT CONCAT(CAST(LENGTH AS CHAR), 'cm') AS MAX_LENGTH
FROM FISH_INFO
WHERE LENGTH IS NOT NULL
ORDER BY LENGTH DESC
LIMIT 1;

# SELECT CONCAT(CAST(MAX(LENGTH) AS CHAR), 'cm') AS MAX_LENGTH
# FROM FISH_INFO