-- 코드를 입력하세요
# SELECT A.TITLE, A.BOARD_ID, B.REPLY_ID, B.WRITER_ID, B.CONTENTS, DATE_FORMAT(B.CREATED_DATE,'%Y-%m-%d')AS CREATED_DATE
# FROM USED_GOODS_BOARD AS A
# JOIN USED_GOODS_REPLY AS B
# ON A.BOARD_ID = B.BOARD_ID
# WHERE YEAR(DATE_FORMAT(A.CREATED_DATE,'%Y-%m-%d')) = '2022' AND MONTH(DATE_FORMAT(A.CREATED_DATE,'%Y-%m-%d')) = '10'
# ORDER BY CREATED_DATE ASC, A.TITLE ASC

SELECT B.TITLE, R.BOARD_ID, R.REPLY_ID, R.WRITER_ID, R.CONTENTS, DATE_FORMAT(R.CREATED_DATE, '%Y-%m-%d') as CREATED_DATE
FROM USED_GOODS_BOARD AS B
JOIN USED_GOODS_REPLY AS R
ON R.BOARD_ID = B.BOARD_ID
WHERE YEAR(R.CREATED_DATE) = '2022' AND MONTH(B.CREATED_DATE) = '10'
ORDER BY R.CREATED_DATE ASC, B.TITLE ASC










